name: package

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: add build details
        run: |
          pip install --pre hamlet-cli
          hamlet engine add-engine-source-build

      - id: get_tag_name
        name: image tag prefix
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo ::set-output name=TAG_NAME::latest
            exit 0
          fi

          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
            exit 0
          fi

          echo ::set-output name=TAG_NAME::test

      - name: build and push container
        if: startsWith(github.ref, 'refs/tags/' )
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: "ghcr.io/${{github.repository}}:${{ steps.get_tag_name.outputs.TAG_NAME }}"
          push: true
          target: base_package
