name: release

on:
  push:
    branches:
      - 'master'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

jobs:
  deploy_tests:
    runs-on: ubuntu-latest

    env:
      HAMLET_ENGINE: aws_testing
      HAMLET_ENGINE_CONFIG: ./

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: |
          pip install hamlet cfn-lint

      - name: Run Tests
        run: |
          hamlet -i mock -p aws -p awstest -f cf deploy test-deployments -p '--junitxml=junit.xml' -o 'hamlet_tests/'

  package:
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
    uses: hamlet-io/.github/.github/workflows/engine_image_release.yml@1.1.2
    secrets: inherit
